### ISSUE TITLE
Superadmin?

### ISSUE THREAD

**Issue by regnighc** [Redacted-Games-LLC/Merchant-Empires#5]
@Celdecea 

Hello Sir,

I'm hoping you can offer me some assistance on an issue im experiencing with the Merchant-Empires code.

After following the readme I have set the sign up admin to 'admin' and created a first account called 'admin' which can reach the admin page however all options are locked except user editor. in the readme there is a reference to make the user a superadmin however it doesn't explain how to do that. could you please help advise me what I need to do there?

much appreciated.

**Comment by Celdecea** [comment]
Hello,

**EDIT:**

Oops, I was reading on mobile and I missed your question's point.

In the user editor you can add more user fields. Just add fields with group 'admin' with a value of '1'. The key name is the page you wish to add. For a complete list of admin pages you can take a look at: [www/tmpl/adm/menu.php#L30](https://github.com/Redacted-Games-LLC/Merchant-Empires/blob/master/www/tmpl/adm/menu.php#L30).


**PREVIOUS:**

The 'SIGNUP_ADMIN' is a special define that automatically gives a specified username access upon signing up for the game. See [this code](https://github.com/Redacted-Games-LLC/Merchant-Empires/blob/master/www/hndl/signup.php#L148).  You can set the SIGNUP_ADMIN by editing the [DBCONFIG.TEMPLATE.php](https://github.com/Redacted-Games-LLC/Merchant-Empires/blob/master/www/DBCONFIG.TEMPLATE.php#L61).

Since you've already made your 'admin' username you can grant it powers via the database. You must add two rows to the user_fields table:

    // Give a user_id the power to make admins
    User: user_id
    Group: 'admin'
    Key: 'admin'
    Value: '1'

    User: user_id
    Group: 'admin'
    Key: 'users'
    Value: '1'

**Comment by regnighc** [comment]
> In the user editor you can add more user fields. Just add fields with group 'admin' with a value of '1'. The key name is the page you wish to add. For a complete list of admin pages you can take a look at: www/tmpl/adm/menu.php#L30.



I appreciate the help, this has fixed my problem. There is one other issue i'm racking my brain over, which I will add as a separate issue, hopefully you can help there too.
